# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16wP87EQ4tmzq281ZZ61R2-RC6vRqFHD6
"""

import pandas as pd

df = pd.read_excel("/content/Merged_Higher_Education_Dashboard_50.xlsx")

df.head()

import pandas as pd

# Load dataset
df = pd.read_excel("/content/Merged_Higher_Education_Dashboard_50.xlsx")

# Check dataset
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

# Display first 5 rows
df.head()

import pandas as pd
import numpy as np
from google.colab import files

# =========================================================
# 1. LOAD YOUR DATASET
# =========================================================

input_file = "/content/Merged_Higher_Education_Dashboard_50.xlsx"

df = pd.read_excel(input_file)

print("Dataset loaded successfully")
print("Number of rows:", len(df))
print("Number of columns:", len(df.columns))

print("\nColumns in dataset:")
print(df.columns.tolist())


# =========================================================
# 2. CLEAN COLUMN NAMES
# =========================================================

df.columns = (
    df.columns
    .str.strip()
    .str.replace("\n", " ", regex=False)
    .str.replace("  ", " ", regex=False)
)

print("\nCleaned columns:")
print(df.columns.tolist())


# =========================================================
# 3. FIND COLUMNS AUTOMATICALLY
# =========================================================

def find_column(names):

    for name in names:
        for col in df.columns:
            if col.lower().strip() == name.lower().strip():
                return col

    for name in names:
        for col in df.columns:
            if name.lower() in col.lower():
                return col

    return None


rank_col = find_column([
    "Rank",
    "World Rank",
    "World University Rank",
    "Overall Rank"
])

overall_col = find_column([
    "Overall Score",
    "Overall"
])

teaching_col = find_column([
    "Teaching",
    "Teaching Score"
])

research_col = find_column([
    "Research",
    "Research Score",
    "Research Environment"
])

citations_col = find_column([
    "Citations",
    "Citations Score"
])

international_col = find_column([
    "International Outlook",
    "International Outlook Score"
])

industry_col = find_column([
    "Industry Income",
    "Industry Income Score"
])

student_staff_col = find_column([
    "Student-Staff Ratio",
    "Student Staff Ratio",
    "Student-to-Staff Ratio"
])


print("\nDetected columns")
print("-------------------------")
print("Rank              :", rank_col)
print("Overall           :", overall_col)
print("Teaching          :", teaching_col)
print("Research          :", research_col)
print("Citations         :", citations_col)
print("International     :", international_col)
print("Industry          :", industry_col)
print("Student-Staff     :", student_staff_col)


# =========================================================
# 4. CONVERT NUMERIC COLUMNS
# =========================================================

columns_to_convert = [
    rank_col,
    overall_col,
    teaching_col,
    research_col,
    citations_col,
    international_col,
    industry_col,
    student_staff_col
]

for col in columns_to_convert:

    if col is not None:

        df[col] = (
            df[col]
            .astype(str)
            .str.replace("%", "", regex=False)
            .str.replace(",", "", regex=False)
            .str.strip()
        )

        df[col] = pd.to_numeric(
            df[col],
            errors="coerce"
        )


# =========================================================
# 5. GLOBAL RANKING SCORE
# =========================================================

if rank_col is not None:

    min_rank = df[rank_col].min()
    max_rank = df[rank_col].max()

    if max_rank != min_rank:

        df["Global Ranking Score"] = (
            (max_rank - df[rank_col])
            /
            (max_rank - min_rank)
        ) * 100

    else:

        df["Global Ranking Score"] = 100


# =========================================================
# 6. RESEARCH IMPACT SCORE
# =========================================================

research_values = []

if research_col is not None:
    research_values.append(df[research_col])

if citations_col is not None:
    research_values.append(df[citations_col])

if research_values:

    df["Research Impact Score"] = pd.concat(
        research_values,
        axis=1
    ).mean(axis=1)


# =========================================================
# 7. TEACHING QUALITY SCORE
# =========================================================

if teaching_col is not None:

    df["Teaching Quality Score"] = df[teaching_col]


# =========================================================
# 8. INTERNATIONALIZATION SCORE
# =========================================================

if international_col is not None:

    df["Internationalization Score"] = (
        df[international_col]
    )


# =========================================================
# 9. INDUSTRY COLLABORATION SCORE
# =========================================================

if industry_col is not None:

    df["Industry Collaboration Score"] = (
        df[industry_col]
    )


# =========================================================
# 10. FACULTY-TO-STUDENT RATIO
# =========================================================

if student_staff_col is not None:

    df["Faculty-to-Student Ratio"] = (
        1 / df[student_staff_col]
    )


# =========================================================
# 11. NORMALIZATION FUNCTION
# =========================================================

def normalize_100(series):

    minimum = series.min()
    maximum = series.max()

    if maximum == minimum:
        return pd.Series(
            100,
            index=series.index
        )

    return (
        (series - minimum)
        /
        (maximum - minimum)
    ) * 100


# =========================================================
# 12. CREATE NORMALIZED KPI SCORES
# =========================================================

if "Global Ranking Score" in df.columns:

    df["Ranking KPI"] = normalize_100(
        df["Global Ranking Score"]
    )


if "Research Impact Score" in df.columns:

    df["Research KPI"] = normalize_100(
        df["Research Impact Score"]
    )


if "Teaching Quality Score" in df.columns:

    df["Teaching KPI"] = normalize_100(
        df["Teaching Quality Score"]
    )


if "Internationalization Score" in df.columns:

    df["International KPI"] = normalize_100(
        df["Internationalization Score"]
    )


if "Industry Collaboration Score" in df.columns:

    df["Industry KPI"] = normalize_100(
        df["Industry Collaboration Score"]
    )


# =========================================================
# 13. OVERALL KPI SCORE
# =========================================================

kpi_columns = [
    "Ranking KPI",
    "Research KPI",
    "Teaching KPI",
    "International KPI",
    "Industry KPI"
]

available_kpis = [
    col for col in kpi_columns
    if col in df.columns
]

df["Overall KPI Score"] = (
    df[available_kpis]
    .mean(axis=1)
)


# =========================================================
# 14. KPI RANK
# =========================================================

df["KPI Rank"] = (
    df["Overall KPI Score"]
    .rank(
        ascending=False,
        method="min"
    )
    .astype(int)
)


# =========================================================
# 15. PERFORMANCE CATEGORY
# =========================================================

def performance_category(score):

    if score >= 80:
        return "Excellent"

    elif score >= 60:
        return "Good"

    elif score >= 40:
        return "Average"

    else:
        return "Needs Improvement"


df["Performance Category"] = (
    df["Overall KPI Score"]
    .apply(performance_category)
)


# =========================================================
# 16. SORT BY KPI RANK
# =========================================================

df = df.sort_values(
    "KPI Rank"
).reset_index(drop=True)


# =========================================================
# 17. ROUND KPI VALUES
# =========================================================

for col in [
    "Global Ranking Score",
    "Research Impact Score",
    "Faculty-to-Student Ratio",
    "Teaching Quality Score",
    "Internationalization Score",
    "Industry Collaboration Score",
    "Ranking KPI",
    "Research KPI",
    "Teaching KPI",
    "International KPI",
    "Industry KPI",
    "Overall KPI Score"
]:

    if col in df.columns:
        df[col] = df[col].round(2)


# =========================================================
# 18. DISPLAY FINAL KPI RESULTS
# =========================================================

print("\n======================================")
print("KPI ENGINEERING COMPLETED")
print("======================================")

print("Total universities:", len(df))

print("\nKPI columns created:")

for col in df.columns:

    if "KPI" in col or "Score" in col or "Ratio" in col:
        print("-", col)


# Display top 10
print("\nTop 10 Universities:")
display(df.head(10))


# =========================================================
# 19. SAVE KPI DATASET
# =========================================================

output_file = (
    "/content/Higher_Education_51_University_KPI.xlsx"
)

df.to_excel(
    output_file,
    index=False
)

print("\nFile created successfully:")
print(output_file)


# =========================================================
# 20. DOWNLOAD EXCEL FILE
# =========================================================

files.download(output_file)

from google.colab import files

files.download("/content/Higher_Education_51_University_KPI.xlsx")