# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15_HlP6t-67ZRR54FeACWc7uf2SmLG2Jf
"""

from google.colab import files

uploaded = files.upload()

print("Uploaded files:")
for filename in uploaded.keys():
    print(filename)

import pandas as pd

the_df = pd.read_csv("THE_World_University_Rankings_50 (3).csv")
qs_df = pd.read_csv("QS_World_University_Rankings_50 (1).csv")

print("THE dataset shape:", the_df.shape)
print("QS dataset shape:", qs_df.shape)

qs_df = qs_df.rename(columns={
    "Overall_Score": "Overall_Score_QS"
})

merged_df = pd.merge(
    qs_df,
    the_df,
    on=["University", "Country"],
    how="inner"
)

print("Merged dataset shape:", merged_df.shape)

display(merged_df)

merged_df.to_csv(
    "Merged_Higher_Education_Dashboard_50.csv",
    index=False
)

print("Merged CSV created successfully!")

print("Rows:", merged_df.shape[0])
print("Columns:", merged_df.shape[1])

display(merged_df.head())

print(merged_df.columns.tolist())

merged_df.columns = (
    merged_df.columns
    .str.strip()
    .str.replace(" ", "_")
)

print(merged_df.columns.tolist())

merged_df["University"] = (
    merged_df["University"]
    .astype(str)
    .str.strip()
)

merged_df["Country"] = (
    merged_df["Country"]
    .astype(str)
    .str.strip()
)

print(
    "Duplicate universities:",
    merged_df["University"].duplicated().sum()
)

merged_df = merged_df.drop_duplicates()

print("Rows after removing duplicates:", len(merged_df))

missing_values = merged_df.isnull().sum()

print(missing_values)

print("Total missing values:",
      merged_df.isnull().sum().sum())

numeric_columns = [
    "QS_Rank",
    "Overall_Score_QS",
    "Academic_Reputation",
    "Employer_Reputation",
    "Citations_per_Faculty",
    "Faculty_Student_Ratio",
    "International_Students",
    "THE_Rank",
    "Overall_Score",
    "Teaching",
    "Research",
    "Citations",
    "Industry_Income",
    "International_Outlook"
]

for column in numeric_columns:
    merged_df[column] = pd.to_numeric(
        merged_df[column],
        errors="coerce"
    )

print(merged_df.dtypes)

print(merged_df.dtypes)



print(merged_df[numeric_columns].isnull().sum())

for column in numeric_columns:
    if merged_df[column].isnull().sum() > 0:
        merged_df[column] = merged_df[column].fillna(
            merged_df[column].median()
        )

print("Invalid QS ranks:",
      (merged_df["QS_Rank"] <= 0).sum())

print("Invalid THE ranks:",
      (merged_df["THE_Rank"] <= 0).sum())

print("QS scores below 0:",
      (merged_df["Overall_Score_QS"] < 0).sum())

print("THE scores below 0:",
      (merged_df["Overall_Score"] < 0).sum())

merged_df["Average_Rank"] = (
    merged_df["QS_Rank"] +
    merged_df["THE_Rank"]
) / 2

merged_df["Average_Overall_Score"] = (
    merged_df["Overall_Score_QS"] +
    merged_df["Overall_Score"]
) / 2

merged_df["Average_Rank"] = merged_df["Average_Rank"].round(2)

merged_df["Average_Overall_Score"] = (
    merged_df["Average_Overall_Score"].round(2)
)



def rank_category(rank):
    if rank <= 10:
        return "Top 10"
    elif rank <= 25:
        return "11-25"
    elif rank <= 50:
        return "26-50"
    else:
        return "Below 50"

merged_df["Rank_Category"] = (
    merged_df["Average_Rank"].apply(rank_category)
)

print("Final rows:", merged_df.shape[0])
print("Final columns:", merged_df.shape[1])

display(merged_df.head(10))

print("===== DATA QUALITY CHECK =====")

print("Rows:", len(merged_df))
print("Columns:", len(merged_df.columns))

print(
    "Duplicate rows:",
    merged_df.duplicated().sum()
)

print(
    "Duplicate universities:",
    merged_df["University"].duplicated().sum()
)

print(
    "Total missing values:",
    merged_df.isnull().sum().sum()
)

print("\nData types:")
print(merged_df.dtypes)

merged_df.to_csv(
    "Cleaned_Transformed_Higher_Education_50.csv",
    index=False
)

merged_df.to_excel(
    "Cleaned_Transformed_Higher_Education_50.xlsx",
    index=False
)

print("Cleaned and transformed files created successfully!")

from google.colab import files

files.download(
    "Cleaned_Transformed_Higher_Education_50.xlsx"
)