# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1La4tnJ4s58Gb-HrQ758YthvclLL61rSf
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np

df = pd.read_excel("/content/Merged_Higher_Education_Dashboard_50.xlsx")

df.head()

print(df.columns.tolist())

max_rank = df["QS_Rank"].max()
min_rank = df["QS_Rank"].min()

df["Global_Ranking_Score"] = (
    (max_rank - df["QS_Rank"]) /
    (max_rank - min_rank)
) * 100

df["Global_Ranking_Score"] = df["Global_Ranking_Score"].round(2)

df["Research_Impact_Score"] = (
    df["Research"] * 0.6 +
    df["Citations"] * 0.4
).round(2)

df["Faculty_to_Student_Ratio"] = (
    df["Faculty_Student_Ratio"]
).round(2)

df["International_Student_Percentage"] = (
    df["International_Students"]
).round(2)

df["Academic_Reputation_Score"] = (
    df["Academic_Reputation"]
).round(2)

df["Academic_Reputation_Score"] = (
    df["Academic_Reputation"]
).round(2)

df["Research_Productivity_Index"] = (
    (df["Research"] + df["Citations"] + df["Industry_Income"]) / 3
).round(2)

df[
    [
        "University",
        "Global_Ranking_Score",
        "Research_Impact_Score",
        "Faculty_to_Student_Ratio",
        "International_Student_Percentage",
        "Academic_Reputation_Score",
        "Research_Productivity_Index"
    ]
].head()

df.to_excel("university_final_dataset.xlsx", index=False)

print("KPI Engineering Completed Successfully!")