{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d6c85f85-d745-4597-9568-92ea385672cf",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "49e46987-20dc-46b2-811e-1c0606302144",
   "metadata": {},
   "outputs": [],
   "source": [
    "qs = pd.read_csv(\"2026_QS_World University_Rankings.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "3bd5b58c-8d36-4141-8465-f0cab91994fb",
   "metadata": {},
   "outputs": [],
   "source": [
    "the = pd.read_excel(\"THE World University Rankings 2026.xlsx\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9a6a7f43-a45d-4ae0-b688-a3dae25d7dce",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Rank</th>\n",
       "      <th>Previous Rank</th>\n",
       "      <th>Name</th>\n",
       "      <th>Country/Territory</th>\n",
       "      <th>Region</th>\n",
       "      <th>Size</th>\n",
       "      <th>Focus</th>\n",
       "      <th>Research</th>\n",
       "      <th>Status</th>\n",
       "      <th>Academic Reputation SCORE</th>\n",
       "      <th>...</th>\n",
       "      <th>International student  RANK</th>\n",
       "      <th>International Students Diversity SCORE</th>\n",
       "      <th>International Students Diversity RANK</th>\n",
       "      <th>International Research Network SCORE</th>\n",
       "      <th>International Research Network RANK</th>\n",
       "      <th>Employment Outcomes SCORE</th>\n",
       "      <th>Employment Outcomes RANK</th>\n",
       "      <th>Sustainability SCORE</th>\n",
       "      <th>Sustainability RANK</th>\n",
       "      <th>Overall SCORE</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>153.0</td>\n",
       "      <td>92.3</td>\n",
       "      <td>130.0</td>\n",
       "      <td>94.1</td>\n",
       "      <td>98.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>7</td>\n",
       "      <td>93.8</td>\n",
       "      <td>33</td>\n",
       "      <td>100</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>Imperial College London</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FO</td>\n",
       "      <td>VH</td>\n",
       "      <td>Public</td>\n",
       "      <td>99.6</td>\n",
       "      <td>...</td>\n",
       "      <td>35.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>22.0</td>\n",
       "      <td>97.5</td>\n",
       "      <td>28.0</td>\n",
       "      <td>95.9</td>\n",
       "      <td>68</td>\n",
       "      <td>98.3</td>\n",
       "      <td>7=</td>\n",
       "      <td>99.4</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>Stanford University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>261.0</td>\n",
       "      <td>76.1</td>\n",
       "      <td>230.0</td>\n",
       "      <td>96.5</td>\n",
       "      <td>49.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>2</td>\n",
       "      <td>95.4</td>\n",
       "      <td>19=</td>\n",
       "      <td>98.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Public</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>80.0</td>\n",
       "      <td>98.7</td>\n",
       "      <td>67.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>3</td>\n",
       "      <td>77.9</td>\n",
       "      <td>198=</td>\n",
       "      <td>97.9</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>217.0</td>\n",
       "      <td>60.6</td>\n",
       "      <td>335.0</td>\n",
       "      <td>99.4</td>\n",
       "      <td>8.0</td>\n",
       "      <td>100.0</td>\n",
       "      <td>1</td>\n",
       "      <td>77.8</td>\n",
       "      <td>201=</td>\n",
       "      <td>97.7</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 30 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  Rank Previous Rank                                         Name  \\\n",
       "0    1             1  Massachusetts Institute of Technology (MIT)   \n",
       "1    2             2                      Imperial College London   \n",
       "2    3             6                          Stanford University   \n",
       "3    4             3                         University of Oxford   \n",
       "4    5             4                           Harvard University   \n",
       "\n",
       "          Country/Territory    Region Size Focus Research  \\\n",
       "0  United States of America  Americas    M    CO       VH   \n",
       "1            United Kingdom    Europe    L    FO       VH   \n",
       "2  United States of America  Americas    L    FC       VH   \n",
       "3            United Kingdom    Europe    L    FC       VH   \n",
       "4  United States of America  Americas    L    FC       VH   \n",
       "\n",
       "                   Status  Academic Reputation SCORE  ...  \\\n",
       "0  Private not for Profit                      100.0  ...   \n",
       "1                  Public                       99.6  ...   \n",
       "2  Private not for Profit                      100.0  ...   \n",
       "3                  Public                      100.0  ...   \n",
       "4  Private not for Profit                      100.0  ...   \n",
       "\n",
       "   International student  RANK  International Students Diversity SCORE  \\\n",
       "0                        153.0                                    92.3   \n",
       "1                         35.0                                   100.0   \n",
       "2                        261.0                                    76.1   \n",
       "3                         80.0                                    98.7   \n",
       "4                        217.0                                    60.6   \n",
       "\n",
       "   International Students Diversity RANK  \\\n",
       "0                                  130.0   \n",
       "1                                   22.0   \n",
       "2                                  230.0   \n",
       "3                                   67.0   \n",
       "4                                  335.0   \n",
       "\n",
       "   International Research Network SCORE  International Research Network RANK  \\\n",
       "0                                  94.1                                 98.0   \n",
       "1                                  97.5                                 28.0   \n",
       "2                                  96.5                                 49.0   \n",
       "3                                 100.0                                  1.0   \n",
       "4                                  99.4                                  8.0   \n",
       "\n",
       "   Employment Outcomes SCORE  Employment Outcomes RANK  Sustainability SCORE  \\\n",
       "0                      100.0                         7                  93.8   \n",
       "1                       95.9                        68                  98.3   \n",
       "2                      100.0                         2                  95.4   \n",
       "3                      100.0                         3                  77.9   \n",
       "4                      100.0                         1                  77.8   \n",
       "\n",
       "  Sustainability RANK  Overall SCORE  \n",
       "0                  33            100  \n",
       "1                  7=           99.4  \n",
       "2                 19=           98.9  \n",
       "3                198=           97.9  \n",
       "4                201=           97.7  \n",
       "\n",
       "[5 rows x 30 columns]"
      ]
     },
     "execution_count": 5,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qs.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "51e8a50a-8417-4619-946d-103d76943a86",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Rank</th>\n",
       "      <th>Name</th>\n",
       "      <th>Country</th>\n",
       "      <th>Student Population</th>\n",
       "      <th>Students to Staff Ratio</th>\n",
       "      <th>International Students</th>\n",
       "      <th>Female to Male Ratio</th>\n",
       "      <th>Overall Score</th>\n",
       "      <th>Teaching</th>\n",
       "      <th>Research Environment</th>\n",
       "      <th>Research Quality</th>\n",
       "      <th>Industry Impact</th>\n",
       "      <th>International Outlook</th>\n",
       "      <th>Year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>22005</td>\n",
       "      <td>10.4</td>\n",
       "      <td>0.43</td>\n",
       "      <td>1900-01-02 04:48:00</td>\n",
       "      <td>98.2100</td>\n",
       "      <td>97.2</td>\n",
       "      <td>100.0</td>\n",
       "      <td>97.7</td>\n",
       "      <td>99.9</td>\n",
       "      <td>96.4</td>\n",
       "      <td>2026</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Massachusetts Institute of Technology</td>\n",
       "      <td>United States</td>\n",
       "      <td>11703</td>\n",
       "      <td>7.7</td>\n",
       "      <td>0.33</td>\n",
       "      <td>1900-01-01 19:57:00</td>\n",
       "      <td>97.6735</td>\n",
       "      <td>99.2</td>\n",
       "      <td>95.3</td>\n",
       "      <td>99.6</td>\n",
       "      <td>100.0</td>\n",
       "      <td>91.9</td>\n",
       "      <td>2026</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Princeton University</td>\n",
       "      <td>United States</td>\n",
       "      <td>8739</td>\n",
       "      <td>8.2</td>\n",
       "      <td>0.23</td>\n",
       "      <td>1900-01-01 23:53:00</td>\n",
       "      <td>97.2110</td>\n",
       "      <td>98.2</td>\n",
       "      <td>97.3</td>\n",
       "      <td>99.0</td>\n",
       "      <td>98.0</td>\n",
       "      <td>85.4</td>\n",
       "      <td>2026</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>University of Cambridge</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>21045</td>\n",
       "      <td>11.3</td>\n",
       "      <td>0.38</td>\n",
       "      <td>1900-01-02 02:50:00</td>\n",
       "      <td>97.2065</td>\n",
       "      <td>96.2</td>\n",
       "      <td>99.9</td>\n",
       "      <td>97.1</td>\n",
       "      <td>87.6</td>\n",
       "      <td>96.3</td>\n",
       "      <td>2026</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Stanford University</td>\n",
       "      <td>United States</td>\n",
       "      <td>17422</td>\n",
       "      <td>5.9</td>\n",
       "      <td>0.25</td>\n",
       "      <td>1900-01-02 00:52:00</td>\n",
       "      <td>97.1510</td>\n",
       "      <td>97.5</td>\n",
       "      <td>97.4</td>\n",
       "      <td>99.5</td>\n",
       "      <td>100.0</td>\n",
       "      <td>83.9</td>\n",
       "      <td>2026</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   Rank                                   Name         Country  \\\n",
       "0     1                   University of Oxford  United Kingdom   \n",
       "1     2  Massachusetts Institute of Technology   United States   \n",
       "2     3                   Princeton University   United States   \n",
       "3     4                University of Cambridge  United Kingdom   \n",
       "4     5                    Stanford University   United States   \n",
       "\n",
       "   Student Population  Students to Staff Ratio  International Students  \\\n",
       "0               22005                     10.4                    0.43   \n",
       "1               11703                      7.7                    0.33   \n",
       "2                8739                      8.2                    0.23   \n",
       "3               21045                     11.3                    0.38   \n",
       "4               17422                      5.9                    0.25   \n",
       "\n",
       "  Female to Male Ratio  Overall Score  Teaching  Research Environment  \\\n",
       "0  1900-01-02 04:48:00        98.2100      97.2                 100.0   \n",
       "1  1900-01-01 19:57:00        97.6735      99.2                  95.3   \n",
       "2  1900-01-01 23:53:00        97.2110      98.2                  97.3   \n",
       "3  1900-01-02 02:50:00        97.2065      96.2                  99.9   \n",
       "4  1900-01-02 00:52:00        97.1510      97.5                  97.4   \n",
       "\n",
       "   Research Quality  Industry Impact  International Outlook  Year  \n",
       "0              97.7             99.9                   96.4  2026  \n",
       "1              99.6            100.0                   91.9  2026  \n",
       "2              99.0             98.0                   85.4  2026  \n",
       "3              97.1             87.6                   96.3  2026  \n",
       "4              99.5            100.0                   83.9  2026  "
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "the.head()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "28248f49-4d75-4445-8eef-cafa4e279dae",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(1504, 30)"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qs.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "8879161c-b031-4516-a935-5130741af5de",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(2191, 14)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "the.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "id": "7dccff03-5558-4aff-b577-b07f06ded559",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Rank', 'Previous Rank', 'Name', 'Country/Territory', 'Region', 'Size',\n",
       "       'Focus', 'Research', 'Status', 'Academic Reputation SCORE',\n",
       "       'Academic Reputation  RANK', 'Employer Reputation SCORE',\n",
       "       'Employer Reputation RANK', 'Faculty Student Ratio SCORE',\n",
       "       'Faculty Student Ratio RANK', 'Citations per Faculty SCORE',\n",
       "       'Citations per Faculty RANK', 'International Faculty  SCORE',\n",
       "       'International Faculty  RANK', 'International Student SCORE',\n",
       "       'International student  RANK', 'International Students Diversity SCORE',\n",
       "       'International Students Diversity RANK',\n",
       "       'International Research Network SCORE',\n",
       "       'International Research Network RANK', 'Employment Outcomes SCORE',\n",
       "       'Employment Outcomes RANK', 'Sustainability SCORE',\n",
       "       'Sustainability RANK', 'Overall SCORE'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "qs.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "id": "955db8fd-9d62-4a32-96e9-9d22bebd156d",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Rank', 'Name', 'Country', 'Student Population',\n",
       "       'Students to Staff Ratio', 'International Students',\n",
       "       'Female to Male Ratio', 'Overall Score', 'Teaching',\n",
       "       'Research Environment', 'Research Quality', 'Industry Impact',\n",
       "       'International Outlook', 'Year'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "the.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "e6dbccab-b830-427b-98a8-f75f3a6b7799",
   "metadata": {},
   "outputs": [],
   "source": [
    "df= pd.concat([qs, the], ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "78dabeaa-2df7-471b-bddd-669b45684b3c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Rank</th>\n",
       "      <th>Previous Rank</th>\n",
       "      <th>Name</th>\n",
       "      <th>Country/Territory</th>\n",
       "      <th>Region</th>\n",
       "      <th>Size</th>\n",
       "      <th>Focus</th>\n",
       "      <th>Research</th>\n",
       "      <th>Status</th>\n",
       "      <th>Academic Reputation SCORE</th>\n",
       "      <th>...</th>\n",
       "      <th>Students to Staff Ratio</th>\n",
       "      <th>International Students</th>\n",
       "      <th>Female to Male Ratio</th>\n",
       "      <th>Overall Score</th>\n",
       "      <th>Teaching</th>\n",
       "      <th>Research Environment</th>\n",
       "      <th>Research Quality</th>\n",
       "      <th>Industry Impact</th>\n",
       "      <th>International Outlook</th>\n",
       "      <th>Year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>Imperial College London</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FO</td>\n",
       "      <td>VH</td>\n",
       "      <td>Public</td>\n",
       "      <td>99.6</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>Stanford University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Public</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 42 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  Rank Previous Rank                                         Name  \\\n",
       "0    1             1  Massachusetts Institute of Technology (MIT)   \n",
       "1    2             2                      Imperial College London   \n",
       "2    3             6                          Stanford University   \n",
       "3    4             3                         University of Oxford   \n",
       "4    5             4                           Harvard University   \n",
       "\n",
       "          Country/Territory    Region Size Focus Research  \\\n",
       "0  United States of America  Americas    M    CO       VH   \n",
       "1            United Kingdom    Europe    L    FO       VH   \n",
       "2  United States of America  Americas    L    FC       VH   \n",
       "3            United Kingdom    Europe    L    FC       VH   \n",
       "4  United States of America  Americas    L    FC       VH   \n",
       "\n",
       "                   Status  Academic Reputation SCORE  ...  \\\n",
       "0  Private not for Profit                      100.0  ...   \n",
       "1                  Public                       99.6  ...   \n",
       "2  Private not for Profit                      100.0  ...   \n",
       "3                  Public                      100.0  ...   \n",
       "4  Private not for Profit                      100.0  ...   \n",
       "\n",
       "   Students to Staff Ratio  International Students  Female to Male Ratio  \\\n",
       "0                      NaN                     NaN                   NaN   \n",
       "1                      NaN                     NaN                   NaN   \n",
       "2                      NaN                     NaN                   NaN   \n",
       "3                      NaN                     NaN                   NaN   \n",
       "4                      NaN                     NaN                   NaN   \n",
       "\n",
       "   Overall Score  Teaching  Research Environment  Research Quality  \\\n",
       "0            NaN       NaN                   NaN               NaN   \n",
       "1            NaN       NaN                   NaN               NaN   \n",
       "2            NaN       NaN                   NaN               NaN   \n",
       "3            NaN       NaN                   NaN               NaN   \n",
       "4            NaN       NaN                   NaN               NaN   \n",
       "\n",
       "   Industry Impact International Outlook  Year  \n",
       "0              NaN                   NaN   NaN  \n",
       "1              NaN                   NaN   NaN  \n",
       "2              NaN                   NaN   NaN  \n",
       "3              NaN                   NaN   NaN  \n",
       "4              NaN                   NaN   NaN  \n",
       "\n",
       "[5 rows x 42 columns]"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "05aa40e8-5cbd-49ee-b440-4d9e597ceaef",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Rank</th>\n",
       "      <th>Previous Rank</th>\n",
       "      <th>Name</th>\n",
       "      <th>Country/Territory</th>\n",
       "      <th>Region</th>\n",
       "      <th>Size</th>\n",
       "      <th>Focus</th>\n",
       "      <th>Research</th>\n",
       "      <th>Status</th>\n",
       "      <th>Academic Reputation SCORE</th>\n",
       "      <th>...</th>\n",
       "      <th>Students to Staff Ratio</th>\n",
       "      <th>International Students</th>\n",
       "      <th>Female to Male Ratio</th>\n",
       "      <th>Overall Score</th>\n",
       "      <th>Teaching</th>\n",
       "      <th>Research Environment</th>\n",
       "      <th>Research Quality</th>\n",
       "      <th>Industry Impact</th>\n",
       "      <th>International Outlook</th>\n",
       "      <th>Year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>1</td>\n",
       "      <td>Massachusetts Institute of Technology (MIT)</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>M</td>\n",
       "      <td>CO</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>2</td>\n",
       "      <td>Imperial College London</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FO</td>\n",
       "      <td>VH</td>\n",
       "      <td>Public</td>\n",
       "      <td>99.6</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>6</td>\n",
       "      <td>Stanford University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>3</td>\n",
       "      <td>University of Oxford</td>\n",
       "      <td>United Kingdom</td>\n",
       "      <td>Europe</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Public</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>4</td>\n",
       "      <td>Harvard University</td>\n",
       "      <td>United States of America</td>\n",
       "      <td>Americas</td>\n",
       "      <td>L</td>\n",
       "      <td>FC</td>\n",
       "      <td>VH</td>\n",
       "      <td>Private not for Profit</td>\n",
       "      <td>100.0</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3690</th>\n",
       "      <td>2187</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Instituto TecnolÃ³gico Metropolitano</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>19.7</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1900-01-01 19:57:00</td>\n",
       "      <td>11.8620</td>\n",
       "      <td>12.9</td>\n",
       "      <td>7.9</td>\n",
       "      <td>9.0</td>\n",
       "      <td>18.7</td>\n",
       "      <td>30.9</td>\n",
       "      <td>2026.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3691</th>\n",
       "      <td>2188</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Universidad Pedagogica y Tecnologica de Colomb...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>18.7</td>\n",
       "      <td>0.00</td>\n",
       "      <td>1900-01-02 07:45:00</td>\n",
       "      <td>11.4340</td>\n",
       "      <td>13.9</td>\n",
       "      <td>8.0</td>\n",
       "      <td>6.0</td>\n",
       "      <td>16.4</td>\n",
       "      <td>34.1</td>\n",
       "      <td>2026.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3692</th>\n",
       "      <td>2189</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Omsk State Technical University</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>17.6</td>\n",
       "      <td>0.08</td>\n",
       "      <td>34 : 66</td>\n",
       "      <td>11.1660</td>\n",
       "      <td>15.6</td>\n",
       "      <td>8.2</td>\n",
       "      <td>5.0</td>\n",
       "      <td>19.9</td>\n",
       "      <td>25.2</td>\n",
       "      <td>2026.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3693</th>\n",
       "      <td>2190</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Federal Institute of Education, Science and Te...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>20.0</td>\n",
       "      <td>0.00</td>\n",
       "      <td>37 : 63</td>\n",
       "      <td>10.8635</td>\n",
       "      <td>12.6</td>\n",
       "      <td>7.1</td>\n",
       "      <td>8.8</td>\n",
       "      <td>17.5</td>\n",
       "      <td>23.3</td>\n",
       "      <td>2026.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3694</th>\n",
       "      <td>2191</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Tula State University</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>...</td>\n",
       "      <td>19.5</td>\n",
       "      <td>0.06</td>\n",
       "      <td>39 : 61</td>\n",
       "      <td>10.2740</td>\n",
       "      <td>14.0</td>\n",
       "      <td>8.4</td>\n",
       "      <td>4.4</td>\n",
       "      <td>17.7</td>\n",
       "      <td>22.4</td>\n",
       "      <td>2026.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>3695 rows × 42 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      Rank Previous Rank                                               Name  \\\n",
       "0        1             1        Massachusetts Institute of Technology (MIT)   \n",
       "1        2             2                            Imperial College London   \n",
       "2        3             6                                Stanford University   \n",
       "3        4             3                               University of Oxford   \n",
       "4        5             4                                 Harvard University   \n",
       "...    ...           ...                                                ...   \n",
       "3690  2187           NaN               Instituto TecnolÃ³gico Metropolitano   \n",
       "3691  2188           NaN  Universidad Pedagogica y Tecnologica de Colomb...   \n",
       "3692  2189           NaN                    Omsk State Technical University   \n",
       "3693  2190           NaN  Federal Institute of Education, Science and Te...   \n",
       "3694  2191           NaN                              Tula State University   \n",
       "\n",
       "             Country/Territory    Region Size Focus Research  \\\n",
       "0     United States of America  Americas    M    CO       VH   \n",
       "1               United Kingdom    Europe    L    FO       VH   \n",
       "2     United States of America  Americas    L    FC       VH   \n",
       "3               United Kingdom    Europe    L    FC       VH   \n",
       "4     United States of America  Americas    L    FC       VH   \n",
       "...                        ...       ...  ...   ...      ...   \n",
       "3690                       NaN       NaN  NaN   NaN      NaN   \n",
       "3691                       NaN       NaN  NaN   NaN      NaN   \n",
       "3692                       NaN       NaN  NaN   NaN      NaN   \n",
       "3693                       NaN       NaN  NaN   NaN      NaN   \n",
       "3694                       NaN       NaN  NaN   NaN      NaN   \n",
       "\n",
       "                      Status  Academic Reputation SCORE  ...  \\\n",
       "0     Private not for Profit                      100.0  ...   \n",
       "1                     Public                       99.6  ...   \n",
       "2     Private not for Profit                      100.0  ...   \n",
       "3                     Public                      100.0  ...   \n",
       "4     Private not for Profit                      100.0  ...   \n",
       "...                      ...                        ...  ...   \n",
       "3690                     NaN                        NaN  ...   \n",
       "3691                     NaN                        NaN  ...   \n",
       "3692                     NaN                        NaN  ...   \n",
       "3693                     NaN                        NaN  ...   \n",
       "3694                     NaN                        NaN  ...   \n",
       "\n",
       "      Students to Staff Ratio  International Students  Female to Male Ratio  \\\n",
       "0                         NaN                     NaN                   NaN   \n",
       "1                         NaN                     NaN                   NaN   \n",
       "2                         NaN                     NaN                   NaN   \n",
       "3                         NaN                     NaN                   NaN   \n",
       "4                         NaN                     NaN                   NaN   \n",
       "...                       ...                     ...                   ...   \n",
       "3690                     19.7                    0.00   1900-01-01 19:57:00   \n",
       "3691                     18.7                    0.00   1900-01-02 07:45:00   \n",
       "3692                     17.6                    0.08               34 : 66   \n",
       "3693                     20.0                    0.00               37 : 63   \n",
       "3694                     19.5                    0.06               39 : 61   \n",
       "\n",
       "      Overall Score  Teaching  Research Environment  Research Quality  \\\n",
       "0               NaN       NaN                   NaN               NaN   \n",
       "1               NaN       NaN                   NaN               NaN   \n",
       "2               NaN       NaN                   NaN               NaN   \n",
       "3               NaN       NaN                   NaN               NaN   \n",
       "4               NaN       NaN                   NaN               NaN   \n",
       "...             ...       ...                   ...               ...   \n",
       "3690        11.8620      12.9                   7.9               9.0   \n",
       "3691        11.4340      13.9                   8.0               6.0   \n",
       "3692        11.1660      15.6                   8.2               5.0   \n",
       "3693        10.8635      12.6                   7.1               8.8   \n",
       "3694        10.2740      14.0                   8.4               4.4   \n",
       "\n",
       "      Industry Impact International Outlook    Year  \n",
       "0                 NaN                   NaN     NaN  \n",
       "1                 NaN                   NaN     NaN  \n",
       "2                 NaN                   NaN     NaN  \n",
       "3                 NaN                   NaN     NaN  \n",
       "4                 NaN                   NaN     NaN  \n",
       "...               ...                   ...     ...  \n",
       "3690             18.7                  30.9  2026.0  \n",
       "3691             16.4                  34.1  2026.0  \n",
       "3692             19.9                  25.2  2026.0  \n",
       "3693             17.5                  23.3  2026.0  \n",
       "3694             17.7                  22.4  2026.0  \n",
       "\n",
       "[3695 rows x 42 columns]"
      ]
     },
     "execution_count": 17,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "e4a92a3b-b709-4566-8164-f668eb13695c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Rank', 'Previous Rank', 'Name', 'Country/Territory', 'Region', 'Size',\n",
       "       'Focus', 'Research', 'Status', 'Academic Reputation SCORE',\n",
       "       'Academic Reputation  RANK', 'Employer Reputation SCORE',\n",
       "       'Employer Reputation RANK', 'Faculty Student Ratio SCORE',\n",
       "       'Faculty Student Ratio RANK', 'Citations per Faculty SCORE',\n",
       "       'Citations per Faculty RANK', 'International Faculty  SCORE',\n",
       "       'International Faculty  RANK', 'International Student SCORE',\n",
       "       'International student  RANK', 'International Students Diversity SCORE',\n",
       "       'International Students Diversity RANK',\n",
       "       'International Research Network SCORE',\n",
       "       'International Research Network RANK', 'Employment Outcomes SCORE',\n",
       "       'Employment Outcomes RANK', 'Sustainability SCORE',\n",
       "       'Sustainability RANK', 'Overall SCORE'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "  qs.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "b5cb88e1-7766-40ad-9f94-a45a03ef2abb",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Rank', 'Name', 'Country', 'Student Population',\n",
       "       'Students to Staff Ratio', 'International Students',\n",
       "       'Female to Male Ratio', 'Overall Score', 'Teaching',\n",
       "       'Research Environment', 'Research Quality', 'Industry Impact',\n",
       "       'International Outlook', 'Year'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 26,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "the.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 66,
   "id": "129acdbc-295d-4c48-a96d-d6260628eba8",
   "metadata": {},
   "outputs": [],
   "source": [
    "the = the.rename(columns={\n",
    "    'Name': 'University Name',\n",
    "    'Student Population': 'Academic Reputation Score',\n",
    "    'Students to Staff Ratio': 'Faculty Student Ratio SCORE',\n",
    "    'International Students': 'International Student SCORE',\n",
    "    'Female to Male Ratio': 'International Students Diversity SCORE',\n",
    "    'Teaching': 'International Faculty  SCORE',\n",
    "    'Research Environment': 'Research SCORE',\n",
    "    'Research Quality' : 'International Research Network SCORE',\n",
    "    'Industry Impact': 'Employment Outcomes SCORE',\n",
    "    'International Outlook': 'Employer Reputation SCORE',\n",
    "    })"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "bc74d877-d101-42fe-ad48-071228934a9e",
   "metadata": {},
   "outputs": [],
   "source": [
    "qs = qs.rename(columns={\n",
    "    'Name': 'University Name',\n",
    "    'Citations per Faculty SCORE': 'Research SCORE',\n",
    "    })\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "02d92357-ad7a-4cab-8e19-0ee27f08a66c",
   "metadata": {},
   "outputs": [],
   "source": [
    "df2 = pd.concat([qs, the], ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 62,
   "id": "017744e1-595e-4450-bbba-d516b01581b0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(3695, 39)"
      ]
     },
     "execution_count": 62,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 63,
   "id": "2decf239-a1e2-41b4-8b7c-31b3227ff890",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Rank',\n",
       " 'University Name',\n",
       " 'Country',\n",
       " 'Size',\n",
       " 'Focus',\n",
       " 'Research',\n",
       " 'Status',\n",
       " 'Academic Reputation SCORE',\n",
       " 'Academic Reputation  RANK',\n",
       " 'Employer Reputation SCORE',\n",
       " 'Employer Reputation RANK',\n",
       " 'Faculty Student Ratio SCORE',\n",
       " 'Faculty Student Ratio RANK',\n",
       " 'Research Score',\n",
       " 'Citations per Faculty RANK',\n",
       " 'International Faculty  SCORE',\n",
       " 'International Faculty  RANK',\n",
       " 'International Student SCORE',\n",
       " 'International student  RANK',\n",
       " 'International Students Diversity SCORE',\n",
       " 'International Students Diversity RANK',\n",
       " 'International Research Network SCORE',\n",
       " 'International Research Network RANK',\n",
       " 'Employment Outcomes SCORE',\n",
       " 'Employment Outcomes RANK',\n",
       " 'Sustainability SCORE',\n",
       " 'Sustainability RANK',\n",
       " 'Overall SCORE',\n",
       " 'Academic Reputation Score',\n",
       " 'Faculty Student Ratio Score',\n",
       " 'International Student Score',\n",
       " 'International Student Diversity Score',\n",
       " 'Overall Score',\n",
       " 'International Faculty Score',\n",
       " 'Research score',\n",
       " 'International Research Network Score',\n",
       " 'Employment Outcomes Score',\n",
       " 'Employer Reputation Score',\n",
       " 'Year']"
      ]
     },
     "execution_count": 63,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2.columns.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 67,
   "id": "8d7c4df5-16a3-4af1-92d9-ac004a65fcdd",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Rank',\n",
       " 'University Name',\n",
       " 'Country',\n",
       " 'Size',\n",
       " 'Focus',\n",
       " 'Research',\n",
       " 'Status',\n",
       " 'Academic Reputation SCORE',\n",
       " 'Academic Reputation  RANK',\n",
       " 'Employer Reputation SCORE',\n",
       " 'Employer Reputation RANK',\n",
       " 'Faculty Student Ratio SCORE',\n",
       " 'Faculty Student Ratio RANK',\n",
       " 'Research Score',\n",
       " 'Citations per Faculty RANK',\n",
       " 'International Faculty  SCORE',\n",
       " 'International Faculty  RANK',\n",
       " 'International Student SCORE',\n",
       " 'International student  RANK',\n",
       " 'International Students Diversity SCORE',\n",
       " 'International Students Diversity RANK',\n",
       " 'International Research Network SCORE',\n",
       " 'International Research Network RANK',\n",
       " 'Employment Outcomes SCORE',\n",
       " 'Employment Outcomes RANK',\n",
       " 'Sustainability SCORE',\n",
       " 'Sustainability RANK',\n",
       " 'Overall SCORE',\n",
       " 'Academic Reputation Score',\n",
       " 'Faculty Student Ratio Score',\n",
       " 'International Student Score',\n",
       " 'International Student Diversity Score',\n",
       " 'Overall Score',\n",
       " 'International Faculty Score',\n",
       " 'Research score',\n",
       " 'International Research Network Score',\n",
       " 'Employment Outcomes Score',\n",
       " 'Employer Reputation Score',\n",
       " 'Year']"
      ]
     },
     "execution_count": 67,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df2.columns.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 70,
   "id": "d3311a15-0603-4568-bba3-5fcebd5a142a",
   "metadata": {},
   "outputs": [],
   "source": [
    "the = the.rename(columns={\n",
    " 'Academic Reputation Score': 'Academic Reputation SCORE',\n",
    " 'Faculty Student Ratio Score': 'Faculty Student Ratio SCORE',\n",
    " 'International Student Score': 'International Student SCORE',\n",
    " 'International Student Diversity Score': 'International Students Diversity SCORE',\n",
    " 'Overall Score': 'Overall SCORE',\n",
    " 'International Faculty Score': 'International Faculty  SCORE',\n",
    " 'International Research Network Score': 'International Research Network SCORE',\n",
    " 'Employment Outcomes Score': 'Employment Outcomes SCORE',\n",
    " 'Employer Reputation Score': 'Employer Reputation SCORE',\n",
    "})\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 71,
   "id": "d6138f6a-8594-498a-b602-7ead8ab2e829",
   "metadata": {},
   "outputs": [],
   "source": [
    "df3 = pd.concat([qs, the], ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 72,
   "id": "ddd76ca7-5a48-430c-8ffa-85cc7ca44cfe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(3695, 30)"
      ]
     },
     "execution_count": 72,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df3.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 73,
   "id": "4c782320-5650-4e46-9839-9221a1413ea6",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "['Rank',\n",
       " 'University Name',\n",
       " 'Country',\n",
       " 'Size',\n",
       " 'Focus',\n",
       " 'Research',\n",
       " 'Status',\n",
       " 'Academic Reputation SCORE',\n",
       " 'Academic Reputation  RANK',\n",
       " 'Employer Reputation SCORE',\n",
       " 'Employer Reputation RANK',\n",
       " 'Faculty Student Ratio SCORE',\n",
       " 'Faculty Student Ratio RANK',\n",
       " 'Research Score',\n",
       " 'Citations per Faculty RANK',\n",
       " 'International Faculty  SCORE',\n",
       " 'International Faculty  RANK',\n",
       " 'International Student SCORE',\n",
       " 'International student  RANK',\n",
       " 'International Students Diversity SCORE',\n",
       " 'International Students Diversity RANK',\n",
       " 'International Research Network SCORE',\n",
       " 'International Research Network RANK',\n",
       " 'Employment Outcomes SCORE',\n",
       " 'Employment Outcomes RANK',\n",
       " 'Sustainability SCORE',\n",
       " 'Sustainability RANK',\n",
       " 'Overall SCORE',\n",
       " 'Research score',\n",
       " 'Year']"
      ]
     },
     "execution_count": 73,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df3.columns.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 74,
   "id": "25e1c3e4-2da9-4962-9abd-ba5c2f053d0a",
   "metadata": {},
   "outputs": [],
   "source": [
    "the = the.rename(columns={\n",
    " 'Research score':  'Research Score',\n",
    "})\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 75,
   "id": "ebed9a4f-474d-4aa1-b8fa-5bce4d2cf551",
   "metadata": {},
   "outputs": [],
   "source": [
    "df4 = pd.concat([qs, the], ignore_index=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 77,
   "id": "75764848-d6c1-47ce-b4a5-2f66198a2ed8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(3695, 29)"
      ]
     },
     "execution_count": 77,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df4.shape"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 79,
   "id": "b346c78d-edbe-4a27-a503-fad23bd6e74f",
   "metadata": {},
   "outputs": [],
   "source": [
    "df4.to_excel(\"data_collection.py.xlsx\", index=False)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bc3ae2ba-9484-4a1e-ba53-11ca987e87f9",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "df4 = pd.read_excel(\"data_collection.py.xlsx\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "2fd102df-abc0-492e-805b-e1d4d054a6c0",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "(3695, 29)"
      ]
     },
     "execution_count": 8,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df4.shape"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "anaconda-2022.05-py39",
   "language": "python",
   "name": "conda-env-anaconda-2022.05-py39-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
